// Source: https://leetcode.com/problems/find-the-difference/
// Title: Find the Difference
// Difficulty: Easy
// Author: Mu Yang <http://muyang.pro>

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// You are given two strings s and t.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Return the letter that was added to t.
//
// Example 1:
//
//   Input: s = "abcd", t = "abcde"
//   Output: "e"
//   Explanation: 'e' is the letter that was added.
//
// Example 2:
//
//   Input: s = "", t = "y"
//   Output: "y"
//
// Constraints:
//
//   0 <= s.length <= 1000
//   t.length == s.length + 1
//   s and t consist of lowercase English letters.
//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

package main

func findTheDifference(s string, t string) byte {
	b := byte(0)

	for i := 0; i < len(s); i++ {
		b ^= s[i]
	}
	for i := 0; i < len(t); i++ {
		b ^= t[i]
	}

	return b
}
